import type { Metadata } from "next";
import React from 'react'

export const metadata: Metadata = {
  title: "About By Parth.",
  description: "Generated by About By Parth.",
};

const page = () => {
  
  return (
    <div>
      About
    </div>
  )
}

export default page
