import type { Metadata } from "next";
import React from 'react'

export const metadata: Metadata = {
    title: "Contact By Parth.",
    description: "Generated by Contact By Parth.",
  };

const page = () => {
  return (
    <div>Contact</div>
  )
}

export default page